[package]
name = "lens-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "lens-worker"
path = "src/main.rs"

[dependencies]
lens-core = { path = "../lens-core" }
lens-project = { path = "../lens-project" }
serde.workspace = true
serde_json.workspace = true
